let GameData = {
    Chances: {
        HYPER: {
            Display: "",
            AltDisplay: "",
            Chance: 5,
            AddedValue: 1,
            Multiplier: 1.2,
            Shared: true,
            BaseColor: "100%",
            Changes: {
                textTransform: "uppercase"
            },
        },
        Hexed: {
            Display: "TUP",
            AltDisplay: "",
            Chance: 10,
            AddedValue: 2,
            Multiplier: 1.5,
            Shared: true,
            BaseColor: "#00ff84",
            Changes: {
                border: "6px solid <BASE>",
            },
        },
        Grayscale: {
            Display: "",
            AltDisplay: "Grayscale",
            Chance: 50,
            AddedValue: 10,
            Multiplier: 2,
            Shared: false,
            BaseColor: "<RANDOM:1-255>",
            Changes: {
                border: "6px solid rgb(<BASE>, <BASE>, <BASE>)",
            },
        },
        Universal: {
            Display: "",
            AltDisplay: "Universal",
            AddedValue: 10,
            Chance: 100,
            Multiplier: 10,
            Shared: false,
            BaseColor: "rgb(<RANDOM:1-255>, <RANDOM:1-255>, <RANDOM:1-255>)",
            Changes: {
                border: "6px solid <BASE>",
                boxShadow: "0px 0px 20px 5px <BASE>",
            },
        },
    },
    Cards: [
        ["Isaiah Cargill", 1],
        ["Jacob Carrell", 1],
        ["Nicholas Chum", 1],
        ["Garnold Crump", 1],
        ["Zander Driesenga", 1],
        ["Thomas Elsie", 1],
        ["Gavin Fetrow", 1],
        ["Nash Finkbeiner", 1],
        ["Lorilei Forbear", 1],
        ["Andrew Haaksma", 1],
        ["Mason Hart", 1],
        ["Joseph Heinz", 1],
        ["Russel Khemphet", 1],
        ["Aaron Meier", 1],
        ["Joseph Meiste", 1],
        ["Jack Peralta Marte", 1],
        ["Lucas Raab", 1],
        ["Jackson Smith", 1],
        ["Matthew Stroud", 1],
        ["Rayne Vanderhulst", 1],
        ["Whitney Wolf", 1],
        ["Seth Woods", 1],
        ["Adryann Cleveland", 5],
        ["Xavier Ick", 5],

        ["Dylan Bruner", 1],
        ["Andrew Creswick", 1],
        ["Joshua Fish", 1],
        ["Anthony Flowers", 1],
        ["Preston Franklin", 1],
        ["Yosgart Garcia", 1],
        ["Thomas Gilligan", 10],
        ["Ryan Haug", 1],
        ["Clyde Hettinga", 1],
        ["Gavin Inman", 1],
        ["Alexander Johnson", 1],
        ["William Newson", 1],
        ["Evan Palma", 1],
        ["Logan Stezowski", 1],
        ["Jacob Woudwyk", 1],
        ["Max Baykowski", 5],
        ["Ashley Berna", 5],
        ["Jacob Daniel", 5],
        ["Ashley Haltenhoff", 5],
        ["Keegan Ohlman", 5],
        ["Alec Tackitt", 5],
        ["Keagan Ziemann-Bell", 5],
        ["Mr. Martinez", 10],
        ["Mr. Luyk", 100],
        ["WicketyOne", 1000],
    ],
    Packs: {
        AM2425: {
            Display: "24-25 AM",
            Image: "",
            Price: 10,
            Cards: [
                "Mr. Luyk",
                "Mr. Martinez",
                "Isaiah Cargill",
                "Jacob Carrell",
                "Nicholas Chum",
                "Garnold Crump",
                "Zander Driesenga",
                "Thomas Elsie",
                "Gavin Fetrow",
                "Nash Finkbeiner",
                "Lorilei Forbear",
                "Andrew Haaksma",
                "Mason Hart",
                "Joseph Heinz",
                "Russel Khemphet",
                "Aaron Meier",
                "Joseph Meiste",
                "Jack Peralta Marte",
                "Lucas Raab",
                "Jackson Smith",
                "Matthew Stroud",
                "Rayne Vanderhulst",
                "Whitney Wolf",
                "Seth Woods",
                "Adryann Cleveland",
                "Xavier Ick",
                "WicketyOne",
            ],
        },
        PM2425: {
            Display: "24-25 PM",
            Image: "",
            Price: 20,
            Cards: [
                "Mr. Luyk",
                "Mr. Martinez",
                "Dylan Bruner",
                "Andrew Creswick",
                "Joshua Fish",
                "Anthony Flowers",
                "Preston Franklin",
                "Yosgart Garcia",
                "Thomas Gilligan", ,
                "Ryan Haug",
                "Clyde Hettinga",
                "Gavin Inman",
                "Alexander Johnson",
                "William Newson",
                "Evan Palma",
                "Logan Stezowski",
                "Jacob Woudwyk",
                "Max Baykowski",
                "Ashley Berna",
                "Jacob Daniel",
                "Ashley Haltenhoff",
                "Keegan Ohlman",
                "Alec Tackitt",
                "Keagan Ziemann-Bell",
                "WicketyOne",
            ],
        },
        /*TEST: {
            Display: "TEST PACK",
            Image: "",
            Price: 1,
            Cards: [
                "Mr. Luyk",
                "Mr. Martinez",
                "Isaiah Cargill",
                "Jacob Carrell",
                "Nicholas Chum",
                "Garnold Crump",
                "Zander Driesenga",
                "Thomas Elsie",
                "Gavin Fetrow",
                "Nash Finkbeiner",
                "Lorilei Forbear",
                "Andrew Haaksma",
                "Mason Hart",
                "Joseph Heinz",
                "Russel Khemphet",
                "Aaron Meier",
                "Joseph Meiste",
                "Jack Peralta Marte",
                "Lucas Raab",
                "Jackson Smith",
                "Matthew Stroud",
                "Rayne Vanderhulst",
                "Whitney Wolf",
                "Seth Woods",
                "Adryann Cleveland",
                "Xavier Ick",
                "Dylan Bruner",
                "Andrew Creswick",
                "Joshua Fish",
                "Anthony Flowers",
                "Preston Franklin",
                "Yosgart Garcia",
                "Thomas Gilligan", ,
                "Ryan Haug",
                "Clyde Hettinga",
                "Gavin Inman",
                "Alexander Johnson",
                "William Newson",
                "Evan Palma",
                "Logan Stezowski",
                "Jacob Woudwyk",
                "Max Baykowski",
                "Ashley Berna",
                "Jacob Daniel",
                "Ashley Haltenhoff",
                "Keegan Ohlman",
                "Alec Tackitt",
                "Keagan Ziemann-Bell",
            ],
        },*/
    },
};
